import type { FastifyInstance } from "fastify";
import type { AppConfig } from "../../config.js";
import type { ContractsConfig } from "../../types/contracts.js";
import {
  loadContractsConfig,
  normalizeContractsConfig,
} from "../../utils/contracts.js";
import { errorResponses } from "../../docs/openapiSchemas.js";

export async function contractRoutes(
  app: FastifyInstance,
  appConfig: AppConfig,
): Promise<void> {
  app.get(
    "/contracts",
    {
      schema: {
        tags: ["Collateral"],
        summary: "Get loaded collateral contract deployment metadata",
        description:
          "Returns the CollateralVault and demo collateral token deployment metadata loaded by the backend. Real deployment metadata is generated by deploy scripts; local Hardhat addresses should not be committed.",
        response: {
          200: {
            description: "Contracts config",
            type: "object",
            additionalProperties: true,
            properties: {
              chainId: { type: "number", example: 31337 },
              network: { type: "string", example: "localhost" },
              mockUSDC: { type: "object", additionalProperties: true },
              collateralVault: { type: "object", additionalProperties: true },
              deployedAt: { type: ["string", "null"] },
              deploymentBlock: { type: ["number", "string", "null"] },
            },
          },
          ...errorResponses,
        },
      },
    },
    async (): Promise<ContractsConfig> => {
      const contracts = await loadContractsConfig(appConfig.contractsFile);
      return normalizeContractsConfig(contracts);
    },
  );
}
